
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: garik
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_first

test:
  <<: *default
  database: first_site_test
