
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: postgres
  password: garik
  host: localhost
  database: rails_first

test:
  <<: *default
  username: postgres
  password: garik
  host: localhost
  database: first_site_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
